name: Build Linux App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    #~ runs-on: ubuntu-latest
    #~ runs-on: ubuntu-20.04
    runs-on: ubuntu-18.04

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install Qt and dependencies
        run: |
          sudo apt-get update
          sudo apt install qtcreator qtbase5-dev qt5-default qtdeclarative5-dev qtdeclarative5-dev-tools libqt5help5 qttools5-dev

      - name: Build
        run: |
          export CC=gcc
          qmake -r genealogymaker.pro CONFIG+=debug_and_release PREFIX=/usr
          make release -j$(nproc)

      - name: Create AppImage
        run: |
          ./ci/build-linux-app-image.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: assets
          path: Genealogy_Maker-*.AppImage
          retention-days: 2
